server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka7003.com:7003/eureka/,http://eureka7001.com:7001/eureka/


spring:
  application:
    name: eureka-7002
