eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eurekaserver/
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: feign-8783
    prefer-ip-address: true

server:
  port: 8783
spring:
  application:
    name: service-feign

feign:
  hystrix:
    enabled: true