server:
  port: 7001

eureka:
  instance:
    hostname: eureka8760.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://eureka8761.com:8761/eureka/


spring:
  application:
    name: eurka-server-8760
