server:
  port: 8763

spring:
  application:
    name: service-hi
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver                                                                                                  #驱动包
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    dbcp2:
      min-idle: 5                                                    #最小维持连接数
      initial-size: 5                                                #初始化连接数
      max-total: 5                                                   #最大连接数
      max-wait-millis: 200                                           #等待链接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: service-hi-8763
    prefer-ip-address: true #访问路劲允许显示ip

info:
  app.name: wudcloud-servicehi
  company.name: 784679322@qq.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}