server:
  port: 8763

spring:
  application:
    name: service-hi
  datasource:
    url: jdbc:mysql://localhost:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/